UvlotApplication/Controllers/LoansController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DataAccessLayerT;
using DataAccessLayerT.DataManager;
using UvlotApplication.Classes;
using System.Drawing.Printing;
using System.Configuration;
using System.Web.Hosting;
using UvlotApplication.HelperClasses;
using System.IO;
using Newtonsoft.Json.Linq;
//using EvoPdf;
using IronPdf;
using ExpertPdf.HtmlToPdf.PdfDocument;
using System.Text;

namespace UvlotApplication.Controllers
{
    public class LoansController : Controller
    {
        // GET: Loans
        //DataProvider dp = new DataProvider();
        DataReader dp = new DataReader();
        DataWriter dw = new DataWriter();
        UvlotEntities uvdb = new UvlotEntities();
        string user = "";
        string LoggedinInst = "";
        public static bool DemoMode = Convert.ToBoolean(ConfigurationManager.AppSettings["DemoMode"]);
        public static string MoneyWaveApiBase = DemoMode
          ? ConfigurationManager.AppSettings["MoneyWave_ApiBase_Test"]
          : ConfigurationManager.AppSettings["MoneyWave_ApiBase_Live"];
        public static string MoneyWaveResolveAccount = $"{MoneyWaveApiBase}{ConfigurationManager.AppSettings["MoneyWaveResolveAccount"]}";
        public static string MoneyWaveVerify = $"{MoneyWaveApiBase}{ConfigurationManager.AppSettings["MoneyWaveVerify"]}";

        public static string MoneyWaveApiKey = DemoMode
           ? ConfigurationManager.AppSettings["MoneyWave_Api_Key_Test"]
           : ConfigurationManager.AppSettings["MoneyWave_Api_Key_Live"];

        public static string MoneyWaveSecretKey = DemoMode
            ? ConfigurationManager.AppSettings["MoneyWave_Secret_Test"]
            : ConfigurationManager.AppSettings["MoneyWave_Secret_Live"];

        [HttpGet]
        public ActionResult ConverttoPdf()
        {
            try
            {

                pdf();
                return View();
                
            }
            catch (Exception ex)
            {
                WebLog.Log(ex.Message.ToString());
                return null;
            }
        }

        public void pdf()
        {
           
            var uri = new Uri("http://localhost:28957/Loans/OfferLetter?Refid=15797962948938");
            var urlToPdf = new HtmlToPdf
            {
                PrintOptions = new PdfPrintOptions()
                {
                   
                    PaperSize = PdfPrintOptions.PdfPaperSize.A4,
                   
                    CssMediaType = PdfPrintOptions.PdfCssMediaType.Print
                },
                // setting login credentials to bypass basic authentication
                LoginCredentials = new HttpLoginCredentials()
                {
                    NetworkUsername = "testUser",
                    NetworkPassword = "testPassword"
                }
            };
            var pdf = urlToPdf.RenderUrlAsPdf(uri);
            pdf.SaveAs("C:/Users/Reliance Limited/Documents/Visual Studio 2015/Projects/UvlotApplication/UvlotApplication/Images/wikipedia.pdf");
            System.Diagnostics.Process.Start("C:/Users/Reliance Limited/Documents/Visual Studio 2015/Projects/UvlotApplication/UvlotApplication/Images/wikipedia.pdf");
        }

        [HttpGet]
        public ActionResult StudentLoan(TableObjects.LoanApplication LoanApp)
        {
            try
            {
                if(LoanApp.Firstname == null || LoanApp.Firstname == "")
                {
                    return RedirectToAction("StudentPreLoan");
                }
                ViewBag.nBanks = dp.GetBanks();
                ViewBag.nRepmtMethods = dp.GetRepaymentMethods();
                ViewBag.nStates = dp.GetNigerianStates();
                ViewBag.nMeansOfIDs = dp.GetMeansOfIdentifications();
                ViewBag.nAccomodationTypes = dp.GetAccomodationTypes();
                ViewBag.nLGAs = dp.GetAllLGAs();
                ViewBag.nTitles = dp.GetTitles();
                ViewBag.nMarital = dp.GetMaritalStatus();
               
                return View();
            }
            catch(Exception ex)
            {
                return null;
            }
        }

        public ActionResult Print()
        {
            try
            {
                
                return View();
            }
            catch(Exception ex)
            {
                WebLog.Log(ex.Message.ToString());
                return null;
            }
        }


        [HttpPost]
        public ActionResult StudentLoan(FormCollection form, TableObjects.LoanApplication lApObj)
        {
            try
            {
               
                string DOB = lApObj.DateOfBirth.ToString();
                DataAccessLayerT.DataManager.LoanApplication inst = new DataAccessLayerT.DataManager.LoanApplication
                {
                    Institution_FK = Convert.ToInt16(form["InstitutionFk"]),
                    AccomodationType_FK = Convert.ToInt32(form["AccomodationTypes"]), //Pending status
                    AccountName = lApObj.AccountName,
                    AccountNumber = lApObj.AccountNumber,
                    ApplicantID = lApObj.IdentficationNumber,
                    ApplicationStatus_FK = 3, //Pending status,
                    BankCode = Convert.ToString(form["Bank"]),
                    BVN = lApObj.BVN,
                    ClosestBusStop = lApObj.ClosestBusStop,
                    ContactAddress = lApObj.ContactAddress,
                    CreatedBy = "", //Change To User ID
                    DateCreated = MyUtility.getCurrentLocalDateTime(),
                    DateModified = MyUtility.getCurrentLocalDateTime(),
                    DateOfBirth = Convert.ToString(lApObj.DateOfBirth),
                    EmailAddress = lApObj.EmailAddress,
                    ExistingLoan = false,//lApObj.ExistingLoan,
                    ExistingLoan_NoOfMonthsLeft = 0,//lApObj.ExistingLoan_NoOfMonthsLeft,
                   ExistingLoan_OutstandingAmount = 0,//lApObj.ExistingLoan_OutstandingAmount,
                    Firstname = lApObj.Firstname,
                    Gender_FK = Convert.ToInt32(form["selectGender"]),
                    IdentficationNumber = lApObj.IdentficationNumber,
                    Landmark = lApObj.Landmark,
                    LGA_FK = Convert.ToInt16(form["lgaList"]),
                    LoanAmount = Convert.ToDouble(lApObj.LoanAmount),
                    LoanComment = "",
                    LoanRefNumber = MyUtility.GenerateRefNo(),
                    LoanTenure = lApObj.LoanTenure,
                    MaritalStatus_FK = Convert.ToInt16(form["Marital"]),
                    MeansOfID_FK = Convert.ToInt32(form["meansOfID"]),
                    NOK_EmailAddress = lApObj.NOK_EmailAddress,
                    NOK_FullName = lApObj.NOK_FullName,
                    NOK_HomeAddress = lApObj.NOK_HomeAddress,
                    NOK_PhoneNumber = lApObj.NOK_PhoneNumber,
                    NOK_Relationship = lApObj.NOK_Relationship,
                    Organization = lApObj.Organization,
                    Othernames = lApObj.Othernames,
                    PhoneNumber = lApObj.PhoneNumber,
                    RepaymentMethod_FK = Convert.ToInt32(form["RepmtMethod"]),
                    StateofResidence_FK = Convert.ToInt32(form["States"]),
                    Surname = lApObj.Surname,
                    Title_FK = Convert.ToInt32(form["Titles"]),
                    IsVisible = 1,
                    ValueDate = MyUtility.getCurrentLocalDateTime().ToString("yyyy/MM/dd"),
                    ValueTime = MyUtility.getCurrentLocalDateTime().ToString("H:mmss"),
                    LoanProduct_FK = 2
                };
                //string mario = form["institutionName"];
                DataWriter.CreateLoanApplication(inst);

                if (inst.ID > 0)
                {
                    StudentLoanDetail empObj = new StudentLoanDetail();
                    empObj.MatricNumber = lApObj.IdentficationNumber;
                    empObj.DateCreated = MyUtility.getCurrentLocalDateTime();
                    empObj.DateModified = MyUtility.getCurrentLocalDateTime();
                    empObj.Department = Convert.ToString(form["department"]);
                    empObj.Faculty = Convert.ToString(form["FACULTY"]);
                    empObj.Institution = lApObj.Organization;
                    empObj.CourseOfStudy = Convert.ToString(form["Course"]);
                    empObj.InstitutionAddress = lApObj.InstitutionAddress;
                    empObj.YearOfAdmission = Convert.ToString(form["Year_admission"]);
                    empObj.YearOfExpectedCompletion = Convert.ToString(form["Year_Completion"]);
                    empObj.CurrentLevel_FK = Convert.ToInt16(form["CurrentLevel"]);
                    empObj.CurrentSemester_FK = Convert.ToInt16(form["CurrentSemester"]);
                    empObj.IsVisible = 1;
                    empObj.LoanApplication_FK = inst.ID;
                    //var loss = form["Los"].ToString();
                    //int los = MyUtility.isNumeric(loss) == true ? Convert.ToInt16(loss) : 0;
                    //string Amount = form["netMonthlyIncome"].ToString();
                   empObj.ValueDate = MyUtility.getCurrentLocalDateTime().ToString("yyyy/MM/dd");
                    empObj.ValueTime = MyUtility.getCurrentLocalDateTime().ToString("H:mmss");
                  
                    DataWriter.CreateStudentLoanDetails(empObj);
                    return RedirectToAction("StuAcknowledgement", new { @Refid = inst.LoanRefNumber });
                    //return View("StuAcknowledgement");
                }
                else
                {
                    return View();
                }
            }
            catch (Exception ex)
            {
                return null;
            }
        }
        [HttpGet]
        public ActionResult StudentPreLoan()
        {

UvlotApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

UvlotApplication/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" href="asset/img/favicon.png" type="image/gif">
    <meta name="description" content="Cash Now Now - loans, savings, payments, agency.">
    <meta name="keywords" content="Cash Now Now - loans, savings, payments, agency.">
    <title>Cash Now Now</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href=@Url.Content("/UserStyles/asset/css/bootstrap.min.css")>
    <link rel="stylesheet" type="text/css" href=@Url.Content("/UserStyles/asset/css/fontawesome-all.min.css")>
    <link rel="stylesheet" type="text/css" href=@Url.Content("/UserStyles/asset/css/reset.css")>
    <link href="https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href=@Url.Content("/UserStyles/asset/css/style.css")>
    <link rel="stylesheet" type="text/css" href=@Url.Content("/UserStyles/asset/css/responsive.css")>



</head>
<body class="js">
    <div id="preloader"></div>
    <!-- start logo menu area -->
    <!-- start logo menu area -->
    <header class="second-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-2 col-md-2">
                    <div class="second-logo">
                        <a href="index.html"><img src=@Url.Content("/UserStyles/asset/img/logo.png") alt=""></a>
                    </div>
                </div>
                <div class="col-lg-8 col-md-10 menuShift">
                    <div id="cssmenu">
                        <ul>
                            <li>
                                <a href="/">Home</a>

                            </li>
                            <li><a href="about.html">About us </a></li>
                            <li>
                                <a href="services.html">Payroll</a>
                                <ul>

                                    <li><a href="@Url.Action("LoanApplication","Loans")">Loan Application</a></li>
                                    <li><a href="@Url.Action("CheckPayrollLoan","Loans")">check Loan status</a></li>


                                </ul>
                            </li>
                            <li>
                                <a href="services.html">Student</a>
                                <ul>
                                    <li><a href="@Url.Action("CheckEligibility","Loans")">Check Eligibilty</a></li>
                                    <li><a href="@Url.Action("StudentLoan","Loans")">Loan Application</a></li>
                                    <li><a href="@Url.Action("CheckStudentLoanStatus","Loans")">Check Loan Status</a></li>

                                </ul>
                            </li>

                            <!-- <li><a href="#">Eligibility</a></li> -->

                            <li>
                                <a href="#">Resources</a>
                                <ul>



                                    <li><a href="faq.html">FAQ</a></li>
                                    <li><a href="how-it-work.html">How It Works</a></li>
                                    @*<li><a href="apply-now.html">T&C</a></li>*@
                                    <li>@Url.Action("termcondition", "Home")</li>
                                </ul>
                            </li>
                            @*<li><a href="contact.html">Contact us</a></li>*@
                        </ul>
                    </div>
                </div>
                <!--<div class="col-lg-1">
                    <a href="@Url.Action("Signin", "User")" class="btn btn-primary btn-sm"> Login</a>
                </div>-->
                <!-- <div class="col-lg-1">
                        <a href="#" class="btn btn-primary btn-sm"> Register</a>
                    </div> -->


                @if (Session["User"] == null)
                {
                    <div class="col-lg-1">
                        <a href="@Url.Action("Signin", "User")" class="btn btn-primary btn-sm">Login</a>
                    </div>
                    <div class="col-lg-1">
                        <a href="@Url.Action("Signup", "User")" class="btn btn-primary btn-sm">Register</a>
                    </div>
                }
                @if (Session["User"] != null)
                {
                    <div class="col-lg-1">
                        <a href="@Url.Action("index", "Admin")" class="btn btn-primary btn-sm"> Dashboard</a>
                        </div>
                        <div class="col-lg-1">
                            <a href="@Url.Action("LogOut", "User")" class="btn btn-primary btn-sm"> Logout</a>
                            </div>
                            }

                        </div>
        </div>
    </header>
    <!-- /header -->
    <!-- end of logo menu area -->
    <!-- end of header area -->
    
    <!-- end of page header -->
    <!-- /header -->
    <!-- end of logo menu area -->
    <!-- end of header area -->
    @*<div class="page-header01">
        <div class="container">
            <div class="row">
                <div class="col-md-12 text-center ">
                    <h2>Apply Now</h2>
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                            <li class="breadcrumb-item active" aria-current="page">Apply Now</li>
                        </ol>
                    </nav>
                </div>
            </div>
        </div>
    </div>*@
    <!-- end of page header -->
    <div>
        @RenderBody()
    </div>
    <!-- start footer area -->
    <section class="footer-area footer-two section-padding">
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-lg-4">
                    <div class="footer-widget">
                        <div class="footer-title">
                            <h4>About Us</h4>
                        </div>
                        <p>
                            With experience and knowledge uvlot wе’rе hеrе to рrоvіdе уоu wіth fіnаnсіаl ѕоlutіоnѕ fоr аll уоur lеndіng needs. Whether you are lооkіng fоr any kind of loan,
                            оur lending tеаm wіll ,..
                        </p>
                        <div class="footer-two-social">
                            <a href="#" class="fa fa-facebook-f"></a>
                            <a href="#" class="fa fa-twitter"></a>
                            <a href="#" class="fa fa-google-plus"></a>
                            <a href="#" class="fa fa-pinterest"></a>
                            <a href="#" class="fa fa-linkedin"></a>
                            <a href="#" class="fa fa-instagram"></a>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-2">
                    <div class="footer-widget pages-widget">
                        <div class="footer-title">
                            <h4>Resources</h4>
                        </div>
                        <ul>
                            <li><a href="#">How it works</a></li>
                            <li><a href="#">Apply</a></li>
                            <li><a href="#">FAQs </a></li>
                            <li><a href="#">Contact us </a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-md-5 col-lg-3">
                    <div class="footer-widget pages-widget">
                        <div class="footer-title">
                            <h4>Useful Links</h4>
                        </div>
                        <ul>
                            <li><a href="#">How it works</a></li>
                            <li><a href="#">Apply</a></li>
                            <li><a href="#">FAQs </a></li>
                            <li><a href="#">Contact us </a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6">
                    <div class="footer-widget">
                        <div class="footer-title">
                            <h4>Contact us</h4>
                        </div>
                        <div class="contact-widget">
                            <ul>
                                <li>
                                    <div class="icon">
                                        <img src=@Url.Content("/UserStyles/asset/img/map-pin.png") alt="">
                                    </div>
                                    <div class="content">
                                        <p>Cash Now Now 10B, Kingsley Emu Street, Lekki Phase 1, Lagos.</p>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon">
                                        <img src=@Url.Content("/UserStyles/asset/img/envalope-2.png") alt="">
                                    </div>
                                    <div class="content">
                                        <p>
                                            mail@cashnownow.com
                                            <span>reply within 2 Hours</span>
                                        </p>
                                    </div>
                                </li>
                                <li>
                                    <div class="icon">
                                        <img src=@Url.Content("/UserStyles/asset/img/phone01.png") alt="">
                                    </div>
                                    <div class="content">
                                        <p>
                                            +234 806 493 8136
                                            <span>24 Hours Support </span>
                                        </p>
                                    </div>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <div class="copy-right-section second-copyright">
        <div class="container">
            <div class="row">
                <div class="col-md-6 text-left">
                    <div class="copyright-text">
                        <p><i class="fa fa-copyright"></i> 2019 Cash Now Now. All Rights Reserved | Powered by <a href="http://www.paelyt.com" target="_blank">Paelyt Solution</a></p>
                    </div>
                </div>
                <div class="col-md-6 text-right">
                    <ul class="footer-nav">
                        <li><a href="#">Home</a></li>
                        <li><a href="#">About us</a></li>
                        <li><a href="#">Loans</a></li>
                        <li><a href="#">Resources</a></li>
                        <li><a href="#">Contactus</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- end of footer area -->
    <script src=@Url.Content("/userStyles/asset/js/jquery-3.3.1.min.js")></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
    <script src=@Url.Content("/userStyles/asset/js/jquery-ui.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/popper.min.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/bootstrap.min.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/jquery.nice-select.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/menumaker.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/owl.carousel.min.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/slider.js")></script>
    <script src=@Url.Content("/userStyles/asset/js/active.js")></script>
</body>

</html>